# Generated by Django 5.2 on 2025-04-05 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GrupoPermissao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='usuario.grupo')),
                ('permissao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='usuario.permissao')),
            ],
            options={
                'verbose_name': 'Grupo Permissão',
                'verbose_name_plural': 'Grupos Permissões',
                'ordering': ['grupo__nome'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioGrupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuario.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Usuário Grupo',
                'verbose_name_plural': 'Usuários Grupos',
                'ordering': ['usuario__nome'],
                'indexes': [models.Index(fields=['usuario', 'grupo'], name='usuario_usu_usuario_680cc6_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'grupo'), name='unique_usuario_grupo')],
            },
        ),
    ]
