# Generated by Django 5.2 on 2025-04-05 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usuariogrupo',
            name='unique_usuario_grupo',
        ),
        migrations.AlterField(
            model_name='usuariogrupo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuario.grupo'),
        ),
        migrations.AlterField(
            model_name='usuariogrupo',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='usuario.usuario'),
        ),
    ]
