# Generated by Django 5.2 on 2025-06-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariogrupo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='usuariogrupo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='grupo',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='usuario.grupo'),
        ),
        migrations.DeleteModel(
            name='GrupoPermissao',
        ),
        migrations.DeleteModel(
            name='UsuarioGrupo',
        ),
    ]
