# Generated by Django 5.2 on 2025-06-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuariogrupo_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='permissoes',
            field=models.ManyToManyField(blank=True, related_name='grupos', to='usuario.permissao'),
        ),
    ]
