# Generated by Django 5.2 on 2025-05-29 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fluxoAprovacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esteira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Esteira',
                'verbose_name_plural': 'Esteiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EsteiraFluxo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('esteira', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos', to='esteira.esteira')),
                ('fluxo_aprovacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esteira', to='fluxoAprovacao.fluxoaprovacao')),
            ],
            options={
                'verbose_name': 'Esteira do Fluxo de Aprovação',
                'verbose_name_plural': 'Esteiras do Fluxo de Aprovação',
                'indexes': [models.Index(fields=['esteira', 'fluxo_aprovacao'], name='esteira_est_esteira_f5d791_idx')],
            },
        ),
    ]
