# Generated by Django 5.2 on 2025-04-05 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esteira', '0001_initial'),
        ('fluxoAprovacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esteirafluxo',
            name='fluxo_aprovacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='esteira', to='fluxoAprovacao.fluxoaprovacao'),
        ),
        migrations.AddIndex(
            model_name='esteirafluxo',
            index=models.Index(fields=['esteira', 'fluxo_aprovacao'], name='esteira_est_esteira_f5d791_idx'),
        ),
        migrations.AddConstraint(
            model_name='esteirafluxo',
            constraint=models.UniqueConstraint(fields=('esteira', 'fluxo_aprovacao'), name='unique_esteira_fluxo'),
        ),
    ]
