# Generated by Django 5.2 on 2025-04-05 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esteira', '0002_initial'),
        ('fluxoAprovacao', '0002_etapa_alter_etapafluxo_etapa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etapa',
        ),
        migrations.RemoveConstraint(
            model_name='esteirafluxo',
            name='unique_esteira_fluxo',
        ),
        migrations.AlterField(
            model_name='esteirafluxo',
            name='esteira',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos', to='esteira.esteira'),
        ),
        migrations.AlterField(
            model_name='esteirafluxo',
            name='fluxo_aprovacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esteira', to='fluxoAprovacao.fluxoaprovacao'),
        ),
    ]
