# Generated by Django 5.2 on 2025-04-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esteira', '0003_delete_etapa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esteirafluxo',
            options={'verbose_name': 'Esteira do Fluxo de Aprovação', 'verbose_name_plural': 'Esteiras do Fluxo de Aprovação'},
        ),
        migrations.RemoveField(
            model_name='esteirafluxo',
            name='ordem',
        ),
    ]
