# Generated by Django 5.2 on 2025-06-08 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esteira', '0001_initial'),
        ('usuario', '0002_remove_usuariogrupo_grupo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('esteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='esteira.esteira')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='usuario.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoSolicitacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_historico', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_solicitacoes', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='solicitacao.solicitacao')),
            ],
            options={
                'verbose_name': 'Histórico de Solicitação',
                'verbose_name_plural': 'Históricos de Solicitações',
                'ordering': ['data_historico'],
            },
        ),
        migrations.CreateModel(
            name='AnexoSolicitacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_solicitacoes', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='solicitacao.solicitacao')),
            ],
            options={
                'verbose_name': 'Anexo de Solicitação',
                'verbose_name_plural': 'Anexos de Solicitações',
                'ordering': ['data_upload'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['usuario', 'esteira', 'grupo'], name='solicitacao_usuario_c53857_idx'),
        ),
        migrations.AddIndex(
            model_name='historicosolicitacao',
            index=models.Index(fields=['solicitacao', 'usuario'], name='solicitacao_solicit_089150_idx'),
        ),
        migrations.AddIndex(
            model_name='anexosolicitacao',
            index=models.Index(fields=['solicitacao', 'usuario'], name='solicitacao_solicit_49e816_idx'),
        ),
    ]
