# Generated by Django 5.2 on 2025-06-08 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esteira', '0001_initial'),
        ('solicitacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='solicitacao',
            name='solicitacao_usuario_c53857_idx',
        ),
        migrations.RemoveField(
            model_name='solicitacao',
            name='grupo',
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['usuario', 'esteira'], name='solicitacao_usuario_1c070c_idx'),
        ),
    ]
