# Generated by Django 5.2 on 2025-06-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0002_remove_solicitacao_solicitacao_usuario_c53857_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ['data_criacao'], 'permissions': [('pode_criar_solicitacao', 'Pode criar solicitações'), ('pode_editar_solicitacao', 'Pode editar solicitações'), ('pode_deletar_solicitacao', 'Pode deletar solicitações'), ('pode_visualizar_solicitacao', 'Pode visualizar solicitações'), ('pode_adicionar_anexo_solicitacao', 'Pode adicionar anexos a solicitações'), ('pode_visualizar_historico_solicitacao', 'Pode visualizar histórico de solicitações'), ('pode_adicionar_historico_solicitacao', 'Pode adicionar histórico a solicitações'), ('pode_visualizar_anexo_solicitacao', 'Pode visualizar anexos de solicitações'), ('pode_deletar_anexo_solicitacao', 'Pode deletar anexos de solicitações'), ('pode_editar_anexo_solicitacao', 'Pode editar anexos de solicitações'), ('pode_visualizar_solicitacoes_usuario', 'Pode visualizar solicitações de outros usuários'), ('pode_visualizar_solicitacoes_esteira', 'Pode visualizar solicitações de uma esteira específica')], 'verbose_name': 'Solicitação', 'verbose_name_plural': 'Solicitações'},
        ),
    ]
