# Generated by Django 5.2 on 2025-05-29 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esteira', '0001_initial'),
        ('fluxoAprovacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAprovacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_historico', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Histórico de Aprovação',
                'verbose_name_plural': 'Históricos de Aprovação',
                'ordering': ['data_historico'],
            },
        ),
        migrations.CreateModel(
            name='Aprovacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=50)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('esteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes', to='esteira.esteira')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes', to='fluxoAprovacao.etapa')),
            ],
            options={
                'verbose_name': 'Aprovação',
                'verbose_name_plural': 'Aprovações',
            },
        ),
    ]
