# Generated by Django 5.2 on 2025-05-29 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aprovacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aprovacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicoaprovacao',
            name='aprovacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='aprovacao.aprovacao'),
        ),
        migrations.AddField(
            model_name='historicoaprovacao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to=settings.AUTH_USER_MODEL),
        ),
    ]
