# Generated by Django 5.2 on 2025-05-29 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FluxoAprovacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fluxo de Aprovação',
                'verbose_name_plural': 'Fluxos de Aprovação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EtapaFluxo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos_aprovacao', to='fluxoAprovacao.etapa')),
                ('etapa_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_sequentes', to='fluxoAprovacao.etapa')),
                ('fluxo_aprovacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='fluxoAprovacao.fluxoaprovacao')),
            ],
            options={
                'verbose_name': 'Etapa do Fluxo de Aprovação',
                'verbose_name_plural': 'Etapas do Fluxo de Aprovação',
                'ordering': ['etapa'],
                'indexes': [models.Index(fields=['fluxo_aprovacao', 'etapa', 'etapa_anterior'], name='fluxo_etapa_index')],
                'constraints': [models.UniqueConstraint(fields=('fluxo_aprovacao', 'etapa', 'etapa_anterior'), name='unique_fluxo_etapa')],
            },
        ),
    ]
