# Generated by Django 5.2 on 2025-04-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxoAprovacao', '0002_etapa_alter_etapafluxo_etapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapafluxo',
            options={'ordering': ['etapa'], 'verbose_name': 'Etapa do Fluxo de Aprovação', 'verbose_name_plural': 'Etapas do Fluxo de Aprovação'},
        ),
        migrations.RemoveField(
            model_name='etapafluxo',
            name='ordem',
        ),
        migrations.AddField(
            model_name='etapafluxo',
            name='etapa_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_sequentes', to='fluxoAprovacao.etapa'),
        ),
    ]
