# Generated by Django 5.2 on 2025-04-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxoAprovacao', '0003_alter_etapafluxo_options_remove_etapafluxo_ordem_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='etapafluxo',
            name='unique_fluxo_etapa',
        ),
        migrations.RemoveIndex(
            model_name='etapafluxo',
            name='fluxoAprova_fluxo_a_8998dd_idx',
        ),
        migrations.AddIndex(
            model_name='etapafluxo',
            index=models.Index(fields=['fluxo_aprovacao', 'etapa', 'etapa_anterior'], name='fluxo_etapa_index'),
        ),
        migrations.AddConstraint(
            model_name='etapafluxo',
            constraint=models.UniqueConstraint(fields=('fluxo_aprovacao', 'etapa', 'etapa_anterior'), name='unique_fluxo_etapa'),
        ),
    ]
